// Generated by CoffeeScript 1.8.0
(function() {
  this.createCodeMirror = function(parentDomObject) {
    var config, editor;
    config = {
      value: "",
      mode: "javascript",
      vimMode: false,
      indentUnit: 4,
      tabSize: 4,
      lineWrapping: true,
      lineNumbers: true,
      autofocus: false,
      matchBrackets: true,
      autoCloseTags: true,
      collapseRange: true,
      theme: "eclipse",
      foldGutter: true,
      gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter"],
      extraKeys: {
        "Ctrl-Space": "autocomplete",
        Tab: function(cm) {
          var spaces;
          spaces = Array(cm.getOption("indentUnit") + 1).join(" ");
          return cm.replaceSelection(spaces, "end", "+input");
        },
        "Ctrl-Q": function(cm) {
          return cm.foldCode(cm.getCursor());
        },
        "Cmd-/": "toggleComment",
        "Ctrl-/": "toggleComment"
      }
    };
    editor = CodeMirror(parentDomObject, config);
    editor.on("change", function(instance, changeObj) {
      if (typeof saveNotebookLater === "function") {
        saveNotebookLater();
      }
      return typeof parentDomObject._compileLater === "function" ? parentDomObject._compileLater() : void 0;
    });
    return editor;
  };

  CodeMirror.commands.autocomplete = function(cm) {
    return CodeMirror.showHint(cm, CodeMirror.hint.javascript);
  };

}).call(this);

//# sourceMappingURL=cdmirror.js.map
