// Generated by CoffeeScript 1.7.1
(function() {
  var setFullScreen, winHeight;

  this.createCodeMirror = function(parentDomObject) {
    var config, editor;
    config = {
      value: "",
      mode: "javascript",
      lineWrapping: true,
      lineNumbers: false,
      autofocus: false,
      matchBrackets: true,
      autoCloseTags: true,
      collapseRange: true,
      theme: "eclipse",
      foldGutter: true,
      gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter"],
      extraKeys: {
        "Ctrl-Space": "autocomplete",
        Tab: function(cm) {
          var spaces;
          spaces = Array(cm.getOption("indentUnit") + 1).join(" ");
          return cm.replaceSelection(spaces, "end", "+input");
        },
        F2: function(ed) {
          if (ed.getMode().name === "javascript") {
            return foldFunc_brace(ed, ed.getCursor().line);
          } else {
            return foldFunc_tag(ed, ed.getCursor().line);
          }
        },
        "Ctrl-Q": function(cm) {
          return cm.foldCode(cm.getCursor());
        },
        "Alt-F11": function(cm) {
          return setFullScreen(cm, !this.isFullScreen(cm));
        },
        Esc: function(cm) {
          if (this.isFullScreen(cm)) {
            return setFullScreen(cm, false);
          }
        },
        "Cmd-/": "toggleComment",
        "Ctrl-/": "toggleComment"
      }
    };
    editor = CodeMirror(parentDomObject, config);
    editor.on("change", function(instance, changeObj) {
      if (typeof saveNotebookLater === "function") {
        saveNotebookLater();
      }
      return typeof parentDomObject._compileLater === "function" ? parentDomObject._compileLater() : void 0;
    });
    return editor;
  };

  CodeMirror.commands.autocomplete = function(cm) {
    return CodeMirror.showHint(cm, CodeMirror.hint.javascript);
  };

  this.isFullScreen = function(cm) {
    return /\bCodeMirror-fullscreen\b/.test(cm.getWrapperElement().className);
  };

  winHeight = function() {
    return window.innerHeight || (document.documentElement || document.body).clientHeight;
  };

  setFullScreen = function(cm, full) {
    var wrap;
    wrap = cm.getWrapperElement();
    if (full) {
      wrap.className += " CodeMirror-fullscreen";
      wrap.style.height = winHeight() + "px";
      document.documentElement.style.overflow = "hidden";
    } else {
      wrap.className = wrap.className.replace(" CodeMirror-fullscreen", "");
      wrap.style.height = "";
      document.documentElement.style.overflow = "";
    }
    return cm.refresh();
  };

  CodeMirror.on(window, "resize", function() {
    var showing;
    showing = document.body.getElementsByClassName("CodeMirror-fullscreen")[0];
    if (!showing) {
      return;
    }
    return showing.CodeMirror.getWrapperElement().style.height = winHeight() + "px";
  });

}).call(this);

//# sourceMappingURL=cdmirror.map
