// Generated by CoffeeScript 1.7.1
(function() {
  this.createCodeMirror = function(parentDomObject) {
    var config, editor;
    config = {
      value: "",
      mode: "javascript",
      vimMode: false,
      lineWrapping: false,
      lineNumbers: true,
      autofocus: false,
      matchBrackets: true,
      autoCloseTags: true,
      collapseRange: true,
      theme: "eclipse",
      foldGutter: true,
      gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter"],
      extraKeys: {
        "Ctrl-Space": "autocomplete",
        Tab: function(cm) {
          var spaces;
          spaces = Array(cm.getOption("indentUnit") + 1).join(" ");
          return cm.replaceSelection(spaces, "end", "+input");
        },
        "Ctrl-Q": function(cm) {
          return cm.foldCode(cm.getCursor());
        },
        "Cmd-/": "toggleComment",
        "Ctrl-/": "toggleComment"
      }
    };
    editor = CodeMirror(parentDomObject, config);
    editor.on("change", function(instance, changeObj) {
      if (typeof saveNotebookLater === "function") {
        saveNotebookLater();
      }
      return typeof parentDomObject._compileLater === "function" ? parentDomObject._compileLater() : void 0;
    });
    return editor;
  };

  CodeMirror.commands.autocomplete = function(cm) {
    return CodeMirror.showHint(cm, CodeMirror.hint.javascript);
  };


  /*
   *FULL SCREEN functions//////////////BEGIN
  @isFullScreen = (cm) ->
      /\bCodeMirror-fullscreen\b/.test cm.getWrapperElement().className
  
  
  winHeight = ->
      window.innerHeight or (document.documentElement or document.body).clientHeight
  
  
  @setFullScreen = (cm, full) ->
      wrap = cm.getWrapperElement()
      if full
          wrap.className += " CodeMirror-fullscreen"
          wrap.style.height = winHeight() + "px"
          document.documentElement.style.overflow = "hidden"
      else
          wrap.className = wrap.className.replace(" CodeMirror-fullscreen", "")
          wrap.style.height = ""
          document.documentElement.style.overflow = ""
      cm.refresh()
  
  
  CodeMirror.on window, "resize", ->
      showing = document.body.getElementsByClassName("CodeMirror-fullscreen")[0]
      return    unless showing
      showing.CodeMirror.getWrapperElement().style.height = winHeight() + "px"
   *FULL SCREEN functions//////////////END
   */

}).call(this);

//# sourceMappingURL=cdmirror.map
