// Generated by CoffeeScript 1.7.1
(function() {
  var buildNotebookList, show_list, storage;

  buildNotebookList = (function(_this) {
    return function(data) {
      var key_name, key_names, last_access, last_owner, name_parts, notebook_access, notebook_name, notebook_owner, s, _i, _len;
      key_names = data.split("\n");
      s = "";
      last_owner = "";
      last_access = "";
      for (_i = 0, _len = key_names.length; _i < _len; _i++) {
        key_name = key_names[_i];
        name_parts = key_name.split("/");
        if (name_parts.length < 3) {
          continue;
        }
        notebook_owner = name_parts[0];
        notebook_access = name_parts[1];
        notebook_name = name_parts[2];
        if (last_owner !== notebook_owner) {
          s += "<div  style='padding-left: 0px;'>" + notebook_owner.replace(/\|.*/, "") + "</div>";
          last_owner = notebook_owner;
        }
        if (last_access !== notebook_access) {
          s += "<div   style='padding-left: 25px; color:" + (notebook_access === "private" ? "black" : "") + ";  '>" + notebook_access + "</div>";
          last_access = notebook_access;
        }
        s += "<div style='padding-left: 50px;'>\n   <a \n   href='/page?owner=" + (encodeURIComponent(notebook_owner)) + "&access=" + (encodeURIComponent(notebook_access)) + "&name=" + (encodeURIComponent(notebook_name)) + "'\n   >" + notebook_name + "</a>&nbsp;&nbsp;&nbsp;\n   <span class='toolButton' title='delete' onclick='deleteNotebook(\"" + key_name + "\")'>&#x00D7</span>\n</div>";
      }
      return $("#notebookList").html(s);
    };
  })(this);

  this.deleteNotebook = function(key_name) {
    if (!confirm("Are you sure?")) {
      return;
    }
    $.ajax({
      url: "/delete",
      dataType: "text",
      data: {
        key_name: key_name
      },
      success: function(data) {
        return setTimeout('location.reload(true)', 100);
      },
      error: function(e) {
        return alert(e);
      }
    });
  };

  show_list = function(url, selector) {
    return $.ajax({
      url: url,
      dataType: 'json',
      success: function(d) {
        var t;
        t = $('<table class="hover" width="100%" ></table>');
        t.hide();
        $(selector).append(t);
        t.dataTable({
          data: d,
          paging: false,
          createdRow: function(row, d, i) {
            var a, key_name, n, net, td0, td0_html, td1, td1_html, tds, u, unet;
            tds = $(row).find('td');
            td0 = tds.first();
            td1 = tds.last();
            u = encodeURIComponent(d.user_name);
            net = encodeURIComponent(d.user_network);
            unet = encodeURIComponent(d.user_name + '|' + d.user_network);
            a = encodeURIComponent(d.access);
            n = encodeURIComponent(d.notebook_name);
            key_name = d.key_name;
            td0_html = "<a href='/page?owner=" + unet + "&access=" + a + "&name=" + n + "' >" + d.notebook_name + "</a>&nbsp;&nbsp;&nbsp;";
            td1_html = "<span class='toolButton' title='delete' onclick='deleteNotebook(\"" + key_name + "\")'>&#x00D7</span>";
            td0.html(td0_html);
            td1.html(td1_html);
            return td1.css('text-align', 'right');
          },
          columns: [
            {
              title: 'Name',
              data: 'notebook_name'
            }, {
              title: 'Acc',
              data: 'access',
              width: 60
            }, {
              title: 'User',
              data: 'user_name',
              width: 120
            }, {
              title: '',
              data: 'access',
              width: 26
            }
          ]
        });
        t.show();
      }
    });
  };

  storage = new NoteBookStorage();

  $(function() {

    /*
    loginHolder =$(".loginHolder")
     * check if login text contains python server template 
    if loginHolder.text().match(/^{{/)
        loginHolder.load "/getloginlink"
     */

    /*
     * check if notebook list contains python server template 
    if $("#notebookList").text().match(/^{{/)
        storage.list buildNotebookList
    else
        buildNotebookList  $("#notebookList").text()
     */
    $("#notebookList").hide();
    show_list('/publiclist', '#publicList');
    show_list('/userlist', '#userList');
    return $("#btnCreate").click(function() {
      var newName;
      newName = "N" + (5000000 + Math.floor(999000 * Math.random()));
      newName = prompt("Change the name", newName);
      if (newName) {
        return document.location.href = "/page?owner=" + encodeURIComponent($(".user_social_name").text()) + "&access=" + encodeURIComponent("public") + "&name=" + encodeURIComponent(newName);
      }
    });
  });

}).call(this);

//# sourceMappingURL=index.html.map
