// Generated by CoffeeScript 1.8.0
(function() {
  var showProperPane, store;

  store = new NoteBookStorage();

  this.deleteNotebook = function(key_name) {
    if (!confirm("Are you sure?")) {
      return;
    }
    return store.del(key_name, function(d) {
      if (d.error) {
        return alert(d.error);
      } else {
        return setTimeout('location.reload(true)', 100);
      }
    }, function(err) {
      return alert("Deleting Error" + err);
    });
  };

  showProperPane = function() {
    if (!$(".user_name").text()) {
      return $('.userTab').hide();
    } else {
      $('.userTab').tab('show');
      $('#publicPane').removeClass('active');
      return $('#userPane').addClass('active');
    }
  };

  $(function() {
    $("#notebookList").hide();
    show_list('/publiclist', '#publicList', store);
    show_list('/userlist', '#userList', store);
    showProperPane();
    return $("#btnCreate").click(function() {
      var newName;
      newName = "N" + (5000000 + Math.floor(999000 * Math.random()));
      newName = prompt("Change the name", newName);
      if (newName) {
        return document.location.href = "/page?owner=" + encodeURIComponent($(".user_name").text() + "|" + $(".user_network").text()) + "&access=" + encodeURIComponent("public") + "&name=" + encodeURIComponent(newName);
      }
    });
  });

}).call(this);

//# sourceMappingURL=index.html.js.map
