// Generated by CoffeeScript 1.7.1
(function() {
  var adjust_ui, delete_cookie, get_signed_network_name, on_page_load, on_signin, on_signout, prepareOAuthorization, read_cookie, write_cookie;

  prepareOAuthorization = function() {
    var adjustGUI, buildLoginButtons, buildLogoutButton, checkNetwork, oLogin, oLogout, oauthHolder;
    hello.init({
      facebook: '1517454335144201',
      windows: '0000000044121F60'
    }, {
      redirect_uri: 'http://inote.vadimivlev.com/inote/html/login.html',
      display: 'popup'
    });
    hello.on("auth.login", function(auth) {
      hello(auth.network).api("/me").success(function(r) {
        var $div_, $page_;
        console.log("auth.login");
        console.log(r);
        $page_ = $(".oauthLogin");
        $div_ = $("<div id='profile_'>\n    <img src='" + r.thumbnail + "' style='width:50px; height:50px; border-radius:25px;vertical-align:middle;'/>\n    id: " + r.id + "\n    name: " + r.name + "\n</div>").appendTo($page_);
      });
    });
    hello.on("auth.logout", function(auth) {
      console.log("auth.logout");
      return console.log(auth);
    });
    buildLoginButtons = function(oLogin) {
      var addLoginLink;
      addLoginLink = function(iconClass, network) {
        return $("<a id='" + network + "_login' class='" + iconClass + "' href='' style='text-decoration:none; margin:3px'></a>").appendTo(oLogin).click(function(e) {
          e.preventDefault();
          return hello.login(network);
        });
      };
      addLoginLink("icon-windows", "windows");
      addLoginLink("icon-googleplus", "googleplus");
      addLoginLink("icon-githib", "github");
      addLoginLink("icon-wordpress", "wordpress");
      addLoginLink("icon-twitter", "twitter");
      return addLoginLink("icon-linkedin", "linkedin");
    };
    buildLogoutButton = function(oLogout) {
      var addLogoutLink;
      addLogoutLink = function(iconClass, network) {
        return $("<a id='" + network + "_logout' class='" + iconClass + "' href='' style='text-decoration:none; margin:3px'>logout</a>").appendTo(oLogout).click(function(e) {
          e.preventDefault();
          hello.logout(network, {
            force: true
          });
          return location.reload();
        });
      };
      return addLogoutLink("icon-windows", "windows");
    };
    oauthHolder = $(".oauthHolder");
    oauthHolder.html("");
    oLogin = $("<span id='oLogin'></span>").appendTo(oauthHolder);
    $("<span>Sign in with</span><br><br>").appendTo(oLogin);
    oLogout = $("<span id='oLogout'></span>").appendTo(oauthHolder);
    buildLoginButtons(oLogin);
    buildLogoutButton(oLogout);
    checkNetwork = function(network) {
      var butIn, butOut, r;
      r = hello(network).getAuthResponse();
      butIn = oLogin.find("#" + network + "_login");
      butOut = oLogout.find("#" + network + "_logout");
      if (r) {
        oLogin.hide();
        butIn.hide();
        butOut.show();
        return console.log(r);
      } else {
        oLogin.show();
        butIn.show();
        return butOut.hide();
      }
    };
    adjustGUI = function() {
      checkNetwork("windows");
      return console.log("adjustGUI");
    };
    return adjustGUI();
  };

  hello.init({
    facebook: '1517454335144201',
    windows: '0000000044121F60'
  }, {
    redirect_uri: 'http://inote.vadimivlev.com/inote/html/login.html',
    display: 'popup'
  });

  hello.on("auth.login", function(auth) {
    return hello(auth.network).api("/me").success(function(r) {
      console.log("auth.login");
      console.log(r);
      return on_signin(r);
    });
  });

  hello.on("auth.logout", function(auth) {
    console.log("auth.logout");
    console.log(auth);
    return on_signout();
  });

  write_cookie = function(r) {
    $.cookie('network', r.network, {
      expires: 7,
      path: '/'
    });
    $.cookie('id', r.id, {
      expires: 7,
      path: '/'
    });
    $.cookie('name', r.name, {
      expires: 7,
      path: '/'
    });
    $.cookie('thumbnail', r.thumbnail, {
      expires: 7,
      path: '/'
    });
  };

  read_cookie = function() {
    return {
      network: $.cookie('network'),
      id: $.cookie('id'),
      name: $.cookie('name'),
      thumbnail: $.cookie('thumbnail')
    };
  };

  delete_cookie = function() {
    $.removeCookie('network', {
      path: '/'
    });
    $.removeCookie('id', {
      path: '/'
    });
    $.removeCookie('name', {
      path: '/'
    });
    $.removeCookie('thumbnail', {
      path: '/'
    });
  };

  get_signed_network_name = function() {
    return read_cookie().network;
  };

  adjust_ui = function() {
    var build_signin_ui, build_signout_ui, network_name;
    build_signout_ui = function(network_name) {
      var addLogoutLink, c;
      addLogoutLink = function($container, network) {
        return $("<a id='" + network + "_logout' class='icon-" + network + "' href='' style='text-decoration:none; margin:3px'>logout</a>").click(function(e) {
          e.preventDefault();
          return hello.logout(network, {
            force: true
          });
        }).appendTo(oLogout);
      };
      c = $('.oauthHolder').html('');
      return addLogoutLink(c, network_name);
    };
    build_signin_ui = function() {
      var addLoginLink, c;
      addLoginLink = function($container, network) {
        return $("<a id='" + network + "_login' class='icon-" + network + "' href='' style='text-decoration:none; margin:3px'></a>").click(function(e) {
          e.preventDefault();
          return hello.login(network);
        }).appendTo($container);
      };
      c = $('.oauthHolder').html('');
      addLoginLink(c, "windows");
      addLoginLink(c, "googleplus");
      addLoginLink(c, "github");
      addLoginLink(c, "wordpress");
      addLoginLink(c, "twitter");
      return addLoginLink(c, "linkedin");
    };
    if (network_name = get_signed_network_name()) {
      return build_signout_ui(network_name);
    } else {
      return build_signin_ui();
    }
  };

  on_signin = function(r) {
    write_cookie(r);
    return adjust_ui();
  };

  on_page_load = function() {
    return adjust_ui();
  };

  on_signout = function() {
    delete_cookie();
    return adjust_ui();
  };

  $(function() {
    return on_page_load();
  });

}).call(this);

//# sourceMappingURL=login.html.map
