// Generated by CoffeeScript 1.7.1
(function() {
  var prepareOAuthorization;

  prepareOAuthorization = function() {
    var adjustGUI, buildLoginButtons, buildLogoutButton, checkNetwork, oLogin, oLogout, oauthHolder;
    hello.init({
      facebook: '1517454335144201',
      windows: '0000000044121F60'
    }, {
      redirect_uri: 'http://inote.vadimivlev.com/inote/html/login.html',
      display: 'popup'
    });
    hello.on("auth.login", function(auth) {
      hello(auth.network).api("/me").success(function(r) {
        var $div_, $page_;
        console.log("auth.login");
        console.log(r);
        $page_ = $(".oauthLogin");
        $div_ = $("<div id='profile_'>\n    <img src='" + r.thumbnail + "' style='width:50px; height:50px; border-radius:25px;vertical-align:middle;'/>\n    id: " + r.id + "\n    name: " + r.name + "\n</div>").appendTo($page_);
      });
    });
    hello.on("auth.logout", function(auth) {
      console.log("auth.logout");
      return console.log(auth);
    });
    buildLoginButtons = function(oLogin) {
      var addLoginLink;
      addLoginLink = function(iconClass, network) {
        return $("<a id='" + network + "_login' class='" + iconClass + "' href='' style='text-decoration:none; margin:3px'></a>").appendTo(oLogin).click(function(e) {
          e.preventDefault();
          return hello.login(network);
        });
      };
      addLoginLink("icon-windows", "windows");
      addLoginLink("icon-googleplus", "googleplus");
      addLoginLink("icon-githib", "github");
      addLoginLink("icon-wordpress", "wordpress");
      addLoginLink("icon-twitter", "twitter");
      addLoginLink("icon-linkedin", "linkedin");
      oLogin.append("<br>");
      return oLogin.append("<a href='javascript:window.history.back()'>back</a>");
    };
    buildLogoutButton = function(oLogout) {
      var addLogoutLink;
      addLogoutLink = function(iconClass, network) {
        return $("<a id='" + network + "_logout' class='" + iconClass + "' href='' style='text-decoration:none; margin:3px'>logout</a>").appendTo(oLogout).click(function(e) {
          e.preventDefault();
          hello.logout(network, {
            force: true
          });
          return location.reload();
        });
      };
      addLogoutLink("icon-windows", "windows");
      oLogin.append("<br>");
      return oLogin.append("<a href='javascript:window.history.back()'>back</a>");
    };
    oauthHolder = $(".oauthHolder");
    oauthHolder.html("");
    oLogin = $("<span id='oLogin'></span>").appendTo(oauthHolder);
    $("<span>Login </span>").appendTo(oLogin);
    oLogout = $("<span id='oLogout'></span>").appendTo(oauthHolder);
    buildLoginButtons(oLogin);
    buildLogoutButton(oLogout);
    checkNetwork = function(network) {
      var butIn, butOut, r;
      r = hello(network).getAuthResponse();
      butIn = oLogin.find("#" + network + "_login");
      butOut = oLogout.find("#" + network + "_logout");
      if (r) {
        oLogin.hide();
        butIn.hide();
        butOut.show();
        return console.log(r);
      } else {
        oLogin.show();
        butIn.show();
        return butOut.hide();
      }
    };
    adjustGUI = function() {
      checkNetwork("windows");
      return console.log("adjustGUI");
    };
    return adjustGUI();
  };

  $(function() {
    return prepareOAuthorization();
  });

}).call(this);

//# sourceMappingURL=login.html.map
