// Generated by CoffeeScript 1.7.1
(function() {
  this.NoteBookStorage = (function() {
    function NoteBookStorage() {}

    NoteBookStorage.prototype.list = function(onsuccess, onerror) {
      return $.ajax({
        type: "GET",
        url: "/list",
        dataType: "text",
        success: onsuccess,
        error: onerror
      });
    };

    NoteBookStorage.prototype.get = function(owner_nickname, notebook_name, onsuccess, onerror) {
      return $.ajax({
        type: "GET",
        url: "/read",
        dataType: "text",
        data: {
          owner_nickname: owner_nickname,
          notebook_name: notebook_name
        },
        success: onsuccess,
        error: onerror
      });
    };

    NoteBookStorage.prototype.put = function(access, notebook_name, notebook_content, onsuccess, onerror) {
      return $.ajax({
        type: "POST",
        url: "/write",
        dataType: "text",
        data: {
          notebook_name: notebook_name,
          access: access,
          content: notebook_content
        },
        success: onsuccess,
        error: onerror
      });
    };

    NoteBookStorage.prototype.del = function(key_name, onsuccess, onerror) {
      return $.ajax({
        url: "/delete",
        data: {
          key_name: key_name
        },
        success: function() {
          return typeof onsuccess === "function" ? onsuccess() : void 0;
        },
        error: function(e) {
          return typeof onerror === "function" ? onerror(e) : void 0;
        }
      });
    };

    return NoteBookStorage;

  })();

}).call(this);

//# sourceMappingURL=notebookstorage.map
