// Generated by CoffeeScript 1.8.0
(function() {
  var T, a;

  T = this;

  a = [1, 2, 3];

  QUnit.test("Проверка количества полей", function(assert) {
    assert.ok(a.length > 0, "количество полей должно быть больше 0");
  });

  QUnit.test("Размер словаря поля name ", function(assert) {
    assert.equal(a.length, 3, "размер должен быть 3");
  });

}).call(this);

//# sourceMappingURL=qunit-tests.js.map
